### ISSUE TITLE
another target with   the same name already exists

### ISSUE THREAD

**Issue by sensiki** [rosbook/effective_robotics_programming_with_ros#1]
at effective_robotics_programming_with_ros/chapter3_tutorials/CMakeLists.txt:57 (add_executable):
  add_executable cannot create target "example4" because another target with  the same name already exists.  The existing target is an executable created  in source directory  "/home/sensiki/dev/catkin_ws/src/effective_robotics_programming_with_ros/chapter2_tutorials".
  See documentation for policy CMP0002 for more details.

**Comment by Anilm3** [comment]
The targets have the same name in both chapter2 and chapter3, before we fix it you can try changing the target names in the CMakeLists.txt of one of them to be able to continue.

**Comment by efernandez** [comment]
@sensiki Are building with:

1. `catkin_make`, or
2. `catkin build`

?

**Comment by efernandez** [comment]
I've just tried again, and with `catkin build` there's no problem.

@sensiki clean your workspace (`rm -rf build devel`) and use `catkin build`. That way you won't have this problem.

**Comment by efernandez** [comment]
I'm going to update the README though, as it says that both flavours should work.

**Comment by efernandez** [comment]
Done.

Also created `kinetic` and `lunar` branches, which for now simply point to `master`.

Thanks @sensiki
