### ISSUE TITLE
error of the catkin_make under the directory of "chapter4_tutorials/robot1_description"

### ISSUE THREAD

**Issue by AustinJia** [rosbook/effective_robotics_programming_with_ros#16]
I was try to following the tutorial of page202 "Watching the 3D model on rviz", but in order to launch to robot1.urdf, I needs to catkin_make the undeer the directory of "effective_robotics_programming_with_ros/chapter4_tutorials/robot1_description", it shows I am unable to do that. 

Does anyone has any suggestions? thanks in advance.

**Comment by AustinJia** [comment]
Solved.

**Comment by wildenali** [comment]
@AustinJia how you solve the this problem?
