### ISSUE TITLE
Chapter 5 tutorials

### ISSUE THREAD

**Issue by rcpilotp51** [rosbook/effective_robotics_programming_with_ros#2]
The tutorial files outlined in the chapter do not exist. Specifically the Homography examples.

**Comment by efernandez** [comment]
@rcpilotp51 The homography example is here: https://github.com/rosbook/effective_robotics_programming_with_ros/tree/master/chapter9_tutorials/src

Please note that chapter 9 is the one that covers computer vision in this new book: https://www.packtpub.com/hardware-and-creative/effective-robotics-programming-ros-third-edition

It looks you're using the previous book.
