### ISSUE TITLE
The Installation

### ISSUE THREAD

**Issue by ClareZhou** [rosbook/effective_robotics_programming_with_ros#3]
I have a problem when I flow the Installation when I put in 
"rosdep install --from-paths src -iy"
It occurred 
"rosbook_arm_pick_and_place: Cannot locate rosdep definition for [moveit_simple_grasps]"

I'm new to ROS ,can you help me

**Comment by cl13554212322** [comment]
download the [moveit_simple_grasps] package and Compile it separately.

**Comment by efernandez** [comment]
Thanks for the feedaback @ClareZhou and your comment @ChenLong-Cristian .

Closing as duplicate of https://github.com/rosbook/effective_robotics_programming_with_ros/issues/5 
Will address it there, thanks.
