### ISSUE TITLE
setup " rosdep install --from-paths src -iy "  error

### ISSUE THREAD

**Issue by naijoug** [rosbook/effective_robotics_programming_with_ros#5]
Ubuntu16.04 + Kinetic

When I set "rosdep install --from-paths src -iy"

This is the error info.

dpkg-query: no packages found matching ros-kinetic-joint-state-controller
dpkg-query: no packages found matching ros-kinetic-gazebo-ros-control
dpkg-query: no packages found matching ros-kinetic-moveit-msgs
dpkg-query: no packages found matching ros-kinetic-moveit-ros-planning-interface
dpkg-query: no packages found matching ros-kinetic-joint-trajectory-controller
dpkg-query: no packages found matching ros-kinetic-moveit-core
dpkg-query: no packages found matching ros-kinetic-fake-localization
dpkg-query: no packages found matching ros-kinetic-joy
dpkg-query: no packages found matching ros-kinetic-control-toolbox
dpkg-query: no packages found matching ros-kinetic-moveit-ros-perception
dpkg-query: no packages found matching ros-kinetic-moveit-ros-visualization
dpkg-query: no packages found matching ros-kinetic-moveit-planners-ompl
dpkg-query: no packages found matching ros-kinetic-joint-limits-interface
dpkg-query: no packages found matching ros-kinetic-dynamixel-msgs
dpkg-query: no packages found matching ros-kinetic-moveit-ros-move-group
dpkg-query: no packages found matching ros-kinetic-hardware-interface
dpkg-query: no packages found matching ros-kinetic-controller-manager
dpkg-query: no packages found matching ros-kinetic-moveit-simple-controller-manager
dpkg-query: no packages found matching ros-kinetic-moveit-fake-controller-manager
dpkg-query: no packages found matching ros-kinetic-map-server
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rosbook_arm_pick_and_place: Cannot locate rosdep definition for [moveit_simple_grasps]

**Comment by lujun723** [comment]
same issue

**Comment by Isanti2016** [comment]
same issue

**Comment by efernandez** [comment]
Thanks for reporting. This is because `moveit_simple_grasps` seems to be deprecated or not maintained any more, so there's no official deb for it.

You'll have to add https://github.com/efernandez/moveit_simple_grasps.git to your workspace as well, and probably https://github.com/pal-robotics/play_motion.git as well.

Could you try, @naijoug @lujun723 @Isanti2016 ?
I'd try to confirm that and update the installation steps here: https://github.com/rosbook/effective_robotics_programming_with_ros

**Comment by efernandez** [comment]
Update the installation instructions: https://github.com/rosbook/effective_robotics_programming_with_ros/blob/master/README.md

The additional step is this one:
``` bash
wstool set moveit_simple_grasps -y --git git@github.com:efernandez/moveit_simple_grasps.git
```

I should be run inside `~/dev/catkin_ws/src` according with the instructions.

Closing issue. Please open another one if you still experience any issue with the installation.
